name: flux
description: Un framework backend modular en Dart, inspirado en NestJS.
version: 1.0.0
# repository: https://github.com/my_org/my_repo (descomentar y ajustar si subes el proyecto a GitHub)

environment:
  sdk: ">=3.5.4 <4.0.0"

# Dependencias necesarias para que Flux funcione correctamente
dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  args: ^2.0.0
  postgres: ^2.4.0
  mysql1: ^0.20.0
  sqlite3: ^1.4.1
  dart_console: ^1.0.0

# Dependencias de desarrollo para linter y pruebas unitarias
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

# Definir el ejecutable del CLI
executables:
  flux: bin/flux.dart
